/*
This is the initial state of the Redux Store.

It returns a function instead of an object to make sure no one can change the initial state.
*/

var C = require('../constants');

function getUrlParameter(name) {
  name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
  var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
  var results = regex.exec(window.location.search);
  return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
}

module.exports = function() {
  return {
    cooler: {
      offsetX: 100,
      offsetY: 100,
      widthFeet: 16,
      widthInches: 0,
      lengthFeet: 22,
      lengthInches: 0,
      vWallCount: 0,
      hWallCount: 0,
      counter: 0,
      selectedConfig: getUrlParameter('Config') || '4',
      config: {
        4: {
          labels: [],
          walls: [
            {
              x: 0,
              y: 0,
              origX: 100,
              origY: 100,
              x0: 100,
              y0: 100,
              x1: 100,
              y1: 500,
              orientation: 'Vertical',
              external: true,
              doors: [],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 375,
              origY: 100,
              x0: 375,
              y0: 100,
              x1: 375,
              y1: 500,
              orientation: 'Vertical',
              external: false,
              doors: [],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 100,
              origY: 500,
              x0: 100,
              y0: 500,
              x1: 650,
              y1: 500,
              orientation: 'Horizontal',
              external: true,
              doors: [],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 100,
              origY: 100,
              x0: 100,
              y0: 100,
              x1: 650,
              y1: 100,
              orientation: 'Horizontal',
              external: true,
              doors: [
                {
                  x: 250,
                  y: 100,
                  direction: 'left',
                  width: 75,
                  index: 0,
                  doorSwing: 'left',
                  doorOpening: 'out',
                  selected: false,
                },
                {
                  x: 500,
                  y: 100,
                  direction: 'right',
                  width: 75,
                  index: 0,
                  doorSwing: 'right',
                  doorOpening: 'in',
                  selected: false,
                },
              ],
              selected: false,
            },
            {
              //  index: 4,
              x: 0,
              y: 0,
              origX: 650,
              origY: 100,
              x0: 650,
              y0: 100,
              x1: 650,
              y1: 500,
              orientation: 'Vertical',
              external: true,
              doors: [],
              selected: false,
            },
          ],
        },
        5: {
          labels: [],
          walls: [
            {
              //index: 0,
              x: 0,
              y: 0,
              origX: 100,
              origY: 100,
              x0: 100,
              y0: 100,
              x1: 100,
              y1: 500,
              orientation: 'Vertical',
              external: true,
              doors: [],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 100,
              origY: 500,
              x0: 100,
              y0: 500,
              x1: 650,
              y1: 500,
              orientation: 'Horizontal',
              external: true,
              doors: [],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 100,
              origY: 100,
              x0: 100,
              y0: 100,
              x1: 650,
              y1: 100,
              orientation: 'Horizontal',
              external: true,
              doors: [
                {
                  x: 250,
                  y: 100,
                  direction: 'left',
                  width: 75,
                  index: 0,
                  doorSwing: 'left',
                  doorOpening: 'out',
                  selected: false,
                },
                {
                  x: 500,
                  y: 100,
                  direction: 'right',
                  width: 75,
                  index: 0,
                  doorSwing: 'right',
                  doorOpening: 'in',
                  selected: false,
                },
              ],
              selected: false,
            },
            {
              x: 0,
              y: 0,
              origX: 650,
              origY: 100,
              x0: 650,
              y0: 100,
              x1: 650,
              y1: 500,
              orientation: 'Vertical',
              external: true,
              doors: [],
              selected: false,
            },
          ],
        },
      },
      walls: [
        {
          x: 0,
          y: 0,
          origX: 100,
          origY: 100,
          x0: 100,
          y0: 100,
          x1: 100,
          y1: 500,
          orientation: 'Vertical',
          external: true,
          doors: [],
          selected: false,
        },
        {
          x: 0,
          y: 0,
          origX: 375,
          origY: 100,
          x0: 375,
          y0: 100,
          x1: 375,
          y1: 500,
          orientation: 'Vertical',
          external: false,
          doors: [],
          selected: false,
        },
        {
          x: 0,
          y: 0,
          origX: 100,
          origY: 500,
          x0: 100,
          y0: 500,
          x1: 650,
          y1: 500,
          orientation: 'Horizontal',
          external: true,
          doors: [],
          selected: false,
        },
        {
          x: 0,
          y: 0,
          origX: 100,
          origY: 100,
          x0: 100,
          y0: 100,
          x1: 650,
          y1: 100,
          orientation: 'Horizontal',
          external: true,
          doors: [
            {
              x: 250,
              y: 100,
              direction: 'left',
              width: 75,
              index: 0,
              doorSwing: 'left',
              doorOpening: 'out',
              selected: false,
            },
            {
              x: 500,
              y: 100,
              direction: 'right',
              width: 75,
              index: 0,
              doorSwing: 'right',
              doorOpening: 'in',
              selected: false,
            },
          ],
          selected: false,
        },
        {
          x: 0,
          y: 0,
          origX: 650,
          origY: 100,
          x0: 650,
          y0: 100,
          x1: 650,
          y1: 500,
          orientation: 'Vertical',
          external: true,
          doors: [],
          selected: false,
        },
      ],
    },
  };
};
