/*
This file contains all constants in the app.
*/

module.exports = {
  // ACTION TYPES
  SELECT_WALL: 'SELECT_WALL',
  ADD_DOOR: 'ADD_DOOR',
  MOVE_DOOR: 'MOVE_DOOR',
  END_DOOR_MOVE: 'END_DOOR_MOVE',
  FLIP_DOOR: 'FLIP_DOOR',
  REVERSE_DOOR: 'REVERSE_DOOR',
  MOVE_WALL: 'MOVE_WALL',
  END_WALL_MOVE: 'END_WALL_MOVE',
  ADD_WALL: 'ADD_WALL',
  DELETE_WALL: 'DELETE_WALL',
  DELETE_DOOR: 'DELETE_DOOR',
  SELECT_DOOR: 'SELECT_DOOR',
  SELECT_CONFIG: 'SELECT_CONFIG',
  ADD_LABEL: 'ADD_LABEL',
  MOVE_LABEL: 'MOVE_LABEL',
  DELETE_LABEL: 'DELETE_LABEL',
  SELECT_LABEL: 'SELECT_LABEL',
  CLEAR_DIAGRAM: 'CLEAR_DIAGRAM',
};
